spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost/testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
