#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://188.68.236.142:3306/kotlin_demo?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw
#    username: ${DEV_DB_USERNAME}
#    password: ${DEV_DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: false
#        show-sql: true
#

